/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as mocks from "./mocks";
export { DeSciPlatform__factory } from "./DeSciPlatform__factory";
export { IpNFT__factory } from "./IpNFT__factory";
